name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "22"

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t nithyanandnadar/spring-app .

      - name: Publish Image to Docker Hub
        run: docker push nithyanandnadar/spring-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image from Docker Hub
        run: docker pull nithyanandnadar/spring-app:latest

      - name: Delete Old Container
        run: docker rm -f spring-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 9000:5000 --name spring-app-container nithyanandnadar/spring-app
